import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'models/notification_model.dart';
import 'fcm_service.dart';

/// Central Notification Service
/// Handles all Firestore operations for notifications
class NotificationService {
  static final NotificationService _instance = NotificationService._internal();
  factory NotificationService() => _instance;
  NotificationService._internal();

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FCMService _fcmService = FCMService();

  /// Get current user ID
  String? get _userId => _auth.currentUser?.uid;

  /// Get notifications collection reference for current user
  CollectionReference? get _notificationsRef {
    if (_userId == null) return null;
    return _firestore
        .collection('notifications')
        .doc(_userId)
        .collection('items');
  }

  /// Create a new notification
  Future<void> createNotification({
    required NotificationSeverity severity,
    required NotificationCategory category,
    required String title,
    required String message,
    Map<String, dynamic>? data,
  }) async {
    if (_userId == null || _notificationsRef == null) return;

    final notification = NotificationModel(
      id: '', // Will be auto-generated by Firestore
      userId: _userId!,
      severity: severity,
      category: category,
      title: title,
      message: message,
      timestamp: DateTime.now(),
      data: data,
    );

    // Save to Firestore
    await _notificationsRef!.add(notification.toFirestore());

    // Send push notification
    await _fcmService.sendLocalNotification(
      title: title,
      message: message,
      severity: severity,
      category: category,
      data: data,
    );
  }

  /// Stream of all notifications for current user
  Stream<List<NotificationModel>>? getNotificationsStream() {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();
    });
  }

  /// Stream of unread notifications count
  Stream<int>? getUnreadCountStream() {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('isRead', isEqualTo: false)
        .snapshots()
        .map((snapshot) => snapshot.docs.length);
  }

  /// Mark notification as read
  Future<void> markAsRead(String notificationId) async {
    if (_notificationsRef == null) return;

    await _notificationsRef!.doc(notificationId).update({
      'isRead': true,
    });
  }

  /// Mark all notifications as read
  Future<void> markAllAsRead() async {
    if (_notificationsRef == null) return;

    final unreadDocs = await _notificationsRef!
        .where('isRead', isEqualTo: false)
        .get();

    final batch = _firestore.batch();
    for (var doc in unreadDocs.docs) {
      batch.update(doc.reference, {'isRead': true});
    }
    await batch.commit();
  }

  /// Delete a notification
  Future<void> deleteNotification(String notificationId) async {
    if (_notificationsRef == null) return;

    await _notificationsRef!.doc(notificationId).delete();
  }

  /// Delete all notifications
  Future<void> deleteAllNotifications() async {
    if (_notificationsRef == null) return;

    final allDocs = await _notificationsRef!.get();
    final batch = _firestore.batch();
    for (var doc in allDocs.docs) {
      batch.delete(doc.reference);
    }
    await batch.commit();
  }

  /// Get notifications by category
  Stream<List<NotificationModel>>? getNotificationsByCategory(
      NotificationCategory category) {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('category', isEqualTo: category.name)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();
    });
  }

  /// Get notifications by severity
  Stream<List<NotificationModel>>? getNotificationsBySeverity(
      NotificationSeverity severity) {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('severity', isEqualTo: severity.name)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();
    });
  }

  /// Mark notification action as taken
  Future<void> markActionTaken(String notificationId) async {
    if (_notificationsRef == null) return;

    await _notificationsRef!.doc(notificationId).update({
      'actionTaken': true,
      'isRead': true,
    });
  }
}
