import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'models/notification_model.dart';
import 'fcm_service.dart';

/// Central Notification Service
/// Handles all Firestore operations for notifications
class NotificationService {
  static final NotificationService _instance = NotificationService._internal();
  factory NotificationService() => _instance;
  NotificationService._internal();

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FCMService _fcmService = FCMService();

  /// Get current user ID
  String? get _userId => _auth.currentUser?.uid;

  /// Get notifications collection reference for current user
  CollectionReference? get _notificationsRef {
    if (_userId == null) return null;
    return _firestore
        .collection('notifications')
        .doc(_userId)
        .collection('items');
  }

  /// Create a new notification
  Future<void> createNotification({
    required NotificationSeverity severity,
    required NotificationCategory category,
    required String title,
    required String message,
    Map<String, dynamic>? data,
  }) async {
    if (_userId == null || _notificationsRef == null) return;

    final notification = NotificationModel(
      id: '', // Will be auto-generated by Firestore
      userId: _userId!,
      severity: severity,
      category: category,
      title: title,
      message: message,
      timestamp: DateTime.now(),
      data: data,
    );

    // Save to Firestore
    await _notificationsRef!.add(notification.toFirestore());

    // Send push notification
    await _fcmService.sendLocalNotification(
      title: title,
      message: message,
      severity: severity,
      category: category,
      data: data,
    );
  }

  /// Stream of all notifications for current user
  /// Combines personal notifications and admin system notifications
  Stream<List<NotificationModel>>? getNotificationsStream() {
    if (_userId == null || _notificationsRef == null) return null;

    // Personal notifications from subcollection
    final personalStream = _notificationsRef!
        .orderBy('timestamp', descending: true)
        .snapshots();

    // Combine personal notifications with admin system notifications
    return personalStream.asyncMap((personalSnapshot) async {
      // Get personal notifications
      final personalNotifs = personalSnapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();

      // Get admin system notifications from flat collection
      final adminSnapshot = await _firestore
          .collection('notifications')
          .where('farmer_id', isEqualTo: _userId)
          .where('sentBy', isEqualTo: 'admin')
          .get();

      final adminNotifs = adminSnapshot.docs.map((doc) {
        final data = doc.data();
        final title = data['title'] ?? 'System Notification';
        final message = data['message'] ?? '';

        // Intelligently categorize admin notifications based on content
        final category = _categorizeAdminNotification(title, message, data);

        // Convert admin notification format to NotificationModel
        return NotificationModel(
          id: doc.id,
          userId: _userId!,
          severity: _parseSeverity(data['type'] ?? 'info'),
          category: category,
          title: title,
          message: message,
          timestamp: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
          isRead: data['read'] ?? false,
          data: {'sentBy': 'admin', 'type': data['type']},
        );
      }).toList();

      // Combine and sort by timestamp
      final combined = [...personalNotifs, ...adminNotifs];
      combined.sort((a, b) => b.timestamp.compareTo(a.timestamp));
      return combined;
    });
  }

  /// Parse severity from admin notification type
  NotificationSeverity _parseSeverity(String type) {
    switch (type.toLowerCase()) {
      case 'alert':
        return NotificationSeverity.critical;
      case 'warning':
        return NotificationSeverity.warning;
      case 'info':
      case 'success':
      default:
        return NotificationSeverity.info;
    }
  }

  /// Categorize admin notifications based on content
  NotificationCategory _categorizeAdminNotification(
    String title,
    String message,
    Map<String, dynamic> data,
  ) {
    final titleLower = title.toLowerCase();
    final messageLower = message.toLowerCase();
    final combinedText = '$titleLower $messageLower';

    // Check if it's explicitly a system notification
    if (data['category'] != null) {
      final categoryStr = data['category'].toString().toLowerCase();
      switch (categoryStr) {
        case 'device':
          return NotificationCategory.device;
        case 'irrigation':
        case 'water':
          return NotificationCategory.irrigation;
        case 'weather':
          return NotificationCategory.weather;
        case 'crop':
          return NotificationCategory.crop;
        case 'system':
        default:
          return NotificationCategory.system;
      }
    }

    // Device-related keywords
    if (combinedText.contains('device') ||
        combinedText.contains('sensor') ||
        combinedText.contains('offline') ||
        combinedText.contains('online') ||
        combinedText.contains('connected') ||
        combinedText.contains('disconnected') ||
        combinedText.contains('esp32')) {
      return NotificationCategory.device;
    }

    // Irrigation/Water-related keywords
    if (combinedText.contains('irrigation') ||
        combinedText.contains('water') ||
        combinedText.contains('pump') ||
        combinedText.contains('valve')) {
      return NotificationCategory.irrigation;
    }

    // Weather-related keywords
    if (combinedText.contains('weather') ||
        combinedText.contains('rain') ||
        combinedText.contains('storm') ||
        combinedText.contains('forecast')) {
      return NotificationCategory.weather;
    }

    // Crop-related keywords
    if (combinedText.contains('crop') ||
        combinedText.contains('harvest') ||
        combinedText.contains('plant') ||
        combinedText.contains('soil')) {
      return NotificationCategory.crop;
    }

    // Default to system for maintenance, updates, etc.
    return NotificationCategory.system;
  }

  /// Stream of unread notifications count
  Stream<int>? getUnreadCountStream() {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('isRead', isEqualTo: false)
        .snapshots()
        .map((snapshot) => snapshot.docs.length);
  }

  /// Mark notification as read
  /// Handles both personal notifications and admin system notifications
  Future<void> markAsRead(String notificationId) async {
    if (_userId == null) return;

    // Try to update in personal subcollection first
    try {
      final personalDoc = await _notificationsRef?.doc(notificationId).get();
      if (personalDoc != null && personalDoc.exists) {
        await _notificationsRef!.doc(notificationId).update({
          'isRead': true,
        });
        return;
      }
    } catch (e) {
      // Document doesn't exist in personal collection
    }

    // Try to update in flat admin notifications collection
    try {
      final adminDoc = await _firestore
          .collection('notifications')
          .doc(notificationId)
          .get();

      if (adminDoc.exists) {
        await _firestore
            .collection('notifications')
            .doc(notificationId)
            .update({
          'read': true,
        });
      }
    } catch (e) {
      // Document doesn't exist in admin collection either
      // Silent fail - notification may have been deleted
    }
  }

  /// Mark all notifications as read
  /// Handles both personal notifications and admin system notifications
  Future<void> markAllAsRead() async {
    if (_userId == null || _notificationsRef == null) return;

    final batch = _firestore.batch();

    // Mark personal notifications as read
    final unreadPersonalDocs = await _notificationsRef!
        .where('isRead', isEqualTo: false)
        .get();

    for (var doc in unreadPersonalDocs.docs) {
      batch.update(doc.reference, {'isRead': true});
    }

    // Mark admin notifications as read
    final unreadAdminDocs = await _firestore
        .collection('notifications')
        .where('farmer_id', isEqualTo: _userId)
        .where('sentBy', isEqualTo: 'admin')
        .where('read', isEqualTo: false)
        .get();

    for (var doc in unreadAdminDocs.docs) {
      batch.update(doc.reference, {'read': true});
    }

    await batch.commit();
  }

  /// Delete a notification
  Future<void> deleteNotification(String notificationId) async {
    if (_notificationsRef == null) return;

    await _notificationsRef!.doc(notificationId).delete();
  }

  /// Delete all notifications
  Future<void> deleteAllNotifications() async {
    if (_notificationsRef == null) return;

    final allDocs = await _notificationsRef!.get();
    final batch = _firestore.batch();
    for (var doc in allDocs.docs) {
      batch.delete(doc.reference);
    }
    await batch.commit();
  }

  /// Get notifications by category
  Stream<List<NotificationModel>>? getNotificationsByCategory(
      NotificationCategory category) {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('category', isEqualTo: category.name)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();
    });
  }

  /// Get notifications by severity
  Stream<List<NotificationModel>>? getNotificationsBySeverity(
      NotificationSeverity severity) {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('severity', isEqualTo: severity.name)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();
    });
  }

  /// Mark notification action as taken
  Future<void> markActionTaken(String notificationId) async {
    if (_notificationsRef == null) return;

    await _notificationsRef!.doc(notificationId).update({
      'actionTaken': true,
      'isRead': true,
    });
  }
}
