import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'models/notification_model.dart';
import 'fcm_service.dart';

/// Central Notification Service
/// Handles all Firestore operations for notifications
class NotificationService {
  static final NotificationService _instance = NotificationService._internal();
  factory NotificationService() => _instance;
  NotificationService._internal();

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FCMService _fcmService = FCMService();

  /// Get current user ID
  String? get _userId => _auth.currentUser?.uid;

  /// Get notifications collection reference for current user
  CollectionReference? get _notificationsRef {
    if (_userId == null) return null;
    return _firestore
        .collection('notifications')
        .doc(_userId)
        .collection('items');
  }

  /// Create a new notification
  Future<void> createNotification({
    required NotificationSeverity severity,
    required NotificationCategory category,
    required String title,
    required String message,
    Map<String, dynamic>? data,
  }) async {
    if (_userId == null || _notificationsRef == null) return;

    final notification = NotificationModel(
      id: '', // Will be auto-generated by Firestore
      userId: _userId!,
      severity: severity,
      category: category,
      title: title,
      message: message,
      timestamp: DateTime.now(),
      data: data,
    );

    // Save to Firestore
    await _notificationsRef!.add(notification.toFirestore());

    // Send push notification
    await _fcmService.sendLocalNotification(
      title: title,
      message: message,
      severity: severity,
      category: category,
      data: data,
    );
  }

  /// Stream of all notifications for current user
  /// Combines personal notifications and admin system notifications
  /// Admin notifications dismissed by the user are filtered out via meta/admin_dismissed
  Stream<List<NotificationModel>>? getNotificationsStream() {
    if (_userId == null || _notificationsRef == null) return null;

    final personalStream = _notificationsRef!
        .orderBy('timestamp', descending: true)
        .snapshots();

    final adminStream = _firestore
        .collection('notifications')
        .where('farmer_id', isEqualTo: _userId)
        .where('sentBy', isEqualTo: 'admin')
        .snapshots();

    final dismissedStream = _firestore
        .collection('notifications')
        .doc(_userId)
        .collection('meta')
        .doc('admin_dismissed')
        .snapshots();

    List<NotificationModel> latestPersonal = [];
    List<NotificationModel> latestAdmin = [];
    Set<String> dismissedAdminIds = {};
    bool personalReady = false;
    bool adminReady = false;
    bool dismissedReady = false;

    late StreamController<List<NotificationModel>> controller;
    StreamSubscription? personalSub;
    StreamSubscription? adminSub;
    StreamSubscription? dismissedSub;

    void emit() {
      if (!personalReady || !adminReady || !dismissedReady) return;
      final filteredAdmin = latestAdmin
          .where((n) => !dismissedAdminIds.contains(n.id))
          .toList();
      final combined = [...latestPersonal, ...filteredAdmin];
      combined.sort((a, b) => b.timestamp.compareTo(a.timestamp));
      controller.add(combined);
    }

    controller = StreamController<List<NotificationModel>>(
      onListen: () {
        personalSub = personalStream.listen(
          (snapshot) {
            // Exclude archived from the main feed — they belong in Archive tab only
            latestPersonal = snapshot.docs
                .map((doc) => NotificationModel.fromFirestore(doc))
                .where((n) => !n.isArchived)
                .toList();
            personalReady = true;
            emit();
          },
          onError: controller.addError,
        );

        adminSub = adminStream.listen(
          (snapshot) {
            latestAdmin = snapshot.docs.map((doc) {
              final data = doc.data();
              final title = data['title'] ?? 'System Notification';
              final message = data['message'] ?? '';
              final category = _categorizeAdminNotification(title, message, data);
              return NotificationModel(
                id: doc.id,
                userId: _userId!,
                severity: _parseSeverity(data['type'] ?? 'info'),
                category: category,
                title: title,
                message: message,
                timestamp: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
                isRead: data['read'] ?? false,
                data: {'sentBy': 'admin', 'type': data['type']},
              );
            }).toList();
            adminReady = true;
            emit();
          },
          onError: controller.addError,
        );

        dismissedSub = dismissedStream.listen(
          (doc) {
            if (doc.exists) {
              final data = doc.data();
              final ids = (data?['ids'] as List<dynamic>?)?.cast<String>() ?? [];
              dismissedAdminIds = ids.toSet();
            } else {
              dismissedAdminIds = {};
            }
            dismissedReady = true;
            emit();
          },
          onError: (_) {
            // If meta doc can't be read, don't block the stream
            dismissedReady = true;
            emit();
          },
        );
      },
      onCancel: () {
        personalSub?.cancel();
        adminSub?.cancel();
        dismissedSub?.cancel();
      },
    );

    return controller.stream;
  }

  /// Parse severity from admin notification type
  NotificationSeverity _parseSeverity(String type) {
    switch (type.toLowerCase()) {
      case 'alert':
        return NotificationSeverity.critical;
      case 'warning':
        return NotificationSeverity.warning;
      case 'info':
      case 'success':
      default:
        return NotificationSeverity.info;
    }
  }

  /// Categorize admin notifications based on content
  NotificationCategory _categorizeAdminNotification(
    String title,
    String message,
    Map<String, dynamic> data,
  ) {
    final titleLower = title.toLowerCase();
    final messageLower = message.toLowerCase();
    final combinedText = '$titleLower $messageLower';

    // Check if it's explicitly a system notification
    if (data['category'] != null) {
      final categoryStr = data['category'].toString().toLowerCase();
      switch (categoryStr) {
        case 'device':
          return NotificationCategory.device;
        case 'irrigation':
        case 'water':
          return NotificationCategory.irrigation;
        case 'weather':
          return NotificationCategory.weather;
        case 'crop':
          return NotificationCategory.crop;
        case 'system':
        default:
          return NotificationCategory.system;
      }
    }

    // Device-related keywords
    if (combinedText.contains('device') ||
        combinedText.contains('sensor') ||
        combinedText.contains('offline') ||
        combinedText.contains('online') ||
        combinedText.contains('connected') ||
        combinedText.contains('disconnected') ||
        combinedText.contains('esp32')) {
      return NotificationCategory.device;
    }

    // Irrigation/Water-related keywords
    if (combinedText.contains('irrigation') ||
        combinedText.contains('water') ||
        combinedText.contains('pump') ||
        combinedText.contains('valve')) {
      return NotificationCategory.irrigation;
    }

    // Weather-related keywords
    if (combinedText.contains('weather') ||
        combinedText.contains('rain') ||
        combinedText.contains('storm') ||
        combinedText.contains('forecast')) {
      return NotificationCategory.weather;
    }

    // Crop-related keywords
    if (combinedText.contains('crop') ||
        combinedText.contains('harvest') ||
        combinedText.contains('plant') ||
        combinedText.contains('soil')) {
      return NotificationCategory.crop;
    }

    // Default to system for maintenance, updates, etc.
    return NotificationCategory.system;
  }

  /// Stream of unread notifications count
  Stream<int>? getUnreadCountStream() {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('isRead', isEqualTo: false)
        .snapshots()
        .map((snapshot) => snapshot.docs.length);
  }

  /// Mark notification as read
  /// Handles both personal notifications and admin system notifications
  Future<void> markAsRead(String notificationId) async {
    if (_userId == null) return;

    // Try to update in personal subcollection first
    try {
      final personalDoc = await _notificationsRef?.doc(notificationId).get();
      if (personalDoc != null && personalDoc.exists) {
        await _notificationsRef!.doc(notificationId).update({
          'isRead': true,
        });
        return;
      }
    } catch (e) {
      // Document doesn't exist in personal collection
    }

    // Try to update in flat admin notifications collection
    try {
      final adminDoc = await _firestore
          .collection('notifications')
          .doc(notificationId)
          .get();

      if (adminDoc.exists) {
        await _firestore
            .collection('notifications')
            .doc(notificationId)
            .update({
          'read': true,
        });
      }
    } catch (e) {
      // Document doesn't exist in admin collection either
      // Silent fail - notification may have been deleted
    }
  }

  /// Mark all notifications as read
  /// Handles both personal notifications and admin system notifications
  Future<void> markAllAsRead() async {
    if (_userId == null || _notificationsRef == null) return;

    final batch = _firestore.batch();

    // Mark personal notifications as read
    final unreadPersonalDocs = await _notificationsRef!
        .where('isRead', isEqualTo: false)
        .get();

    for (var doc in unreadPersonalDocs.docs) {
      batch.update(doc.reference, {'isRead': true});
    }

    // Mark admin notifications as read
    final unreadAdminDocs = await _firestore
        .collection('notifications')
        .where('farmer_id', isEqualTo: _userId)
        .where('sentBy', isEqualTo: 'admin')
        .where('read', isEqualTo: false)
        .get();

    for (var doc in unreadAdminDocs.docs) {
      batch.update(doc.reference, {'read': true});
    }

    await batch.commit();
  }

  /// Mark all personal notifications as read AND archive them in one batch.
  /// Admin notifications are only marked as read (no archive field on that collection).
  Future<void> markAllAsReadAndArchive() async {
    if (_userId == null || _notificationsRef == null) return;

    final batch = _firestore.batch();

    // Personal notifications — mark read + archive in one write per doc
    final personalDocs = await _notificationsRef!.get();
    for (final doc in personalDocs.docs) {
      final data = doc.data() as Map<String, dynamic>;
      final isArchived = data['isArchived'] == true;
      if (!isArchived) {
        batch.update(doc.reference, {'isRead': true, 'isArchived': true});
      }
    }

    // Admin notifications — mark read only (flat collection, no isArchived field)
    final unreadAdminDocs = await _firestore
        .collection('notifications')
        .where('farmer_id', isEqualTo: _userId)
        .where('sentBy', isEqualTo: 'admin')
        .where('read', isEqualTo: false)
        .get();
    for (final doc in unreadAdminDocs.docs) {
      batch.update(doc.reference, {'read': true});
    }

    await batch.commit();
  }

  /// Delete a notification
  Future<void> deleteNotification(String notificationId) async {
    if (_notificationsRef == null) return;

    await _notificationsRef!.doc(notificationId).delete();
  }

  /// Delete all notifications
  Future<void> deleteAllNotifications() async {
    if (_notificationsRef == null) return;

    final allDocs = await _notificationsRef!.get();
    final batch = _firestore.batch();
    for (var doc in allDocs.docs) {
      batch.delete(doc.reference);
    }
    await batch.commit();
  }

  /// Get notifications by category
  Stream<List<NotificationModel>>? getNotificationsByCategory(
      NotificationCategory category) {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('category', isEqualTo: category.name)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();
    });
  }

  /// Get notifications by severity
  Stream<List<NotificationModel>>? getNotificationsBySeverity(
      NotificationSeverity severity) {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .where('severity', isEqualTo: severity.name)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => NotificationModel.fromFirestore(doc))
          .toList();
    });
  }

  /// Mark notification action as taken
  Future<void> markActionTaken(String notificationId) async {
    if (_notificationsRef == null) return;

    await _notificationsRef!.doc(notificationId).update({
      'actionTaken': true,
      'isRead': true,
    });
  }

  /// Archive a single notification — removes from main list, saves in archive.
  /// For admin notifications (stored in the root collection, not user subcollection),
  /// we track dismissal in the user's own meta document instead.
  Future<void> archiveNotification(String notificationId) async {
    if (_userId == null) return;

    // Check if it exists in the personal subcollection first
    try {
      final personalDoc = await _notificationsRef?.doc(notificationId).get();
      if (personalDoc != null && personalDoc.exists) {
        await _notificationsRef!.doc(notificationId).update({
          'isArchived': true,
          'isRead': true,
        });
        return;
      }
    } catch (_) {}

    // Not in personal subcollection — it's an admin notification.
    // Track dismissal in user-owned meta doc (user has write access to their own subcollection).
    try {
      await _firestore
          .collection('notifications')
          .doc(_userId)
          .collection('meta')
          .doc('admin_dismissed')
          .set(
            {'ids': FieldValue.arrayUnion([notificationId])},
            SetOptions(merge: true),
          );
    } catch (_) {}
  }

  /// Restore a notification from archive back to the main list
  Future<void> unarchiveNotification(String notificationId) async {
    if (_notificationsRef == null) return;
    try {
      await _notificationsRef!.doc(notificationId).update({
        'isArchived': false,
      });
    } catch (_) {}
  }

  /// Archive all read notifications in one batch
  Future<void> archiveAllRead() async {
    if (_notificationsRef == null) return;

    final snapshot = await _notificationsRef!.get();
    final batch = _firestore.batch();

    for (final doc in snapshot.docs) {
      final data = doc.data() as Map<String, dynamic>;
      final isRead = data['isRead'] == true;
      final isArchived = data['isArchived'] == true;
      if (isRead && !isArchived) {
        batch.update(doc.reference, {'isArchived': true});
      }
    }

    await batch.commit();
  }

  /// Stream of archived notifications (for the Archive tab)
  Stream<List<NotificationModel>>? getArchivedNotificationsStream() {
    if (_notificationsRef == null) return null;

    return _notificationsRef!
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => NotificationModel.fromFirestore(doc))
            .where((n) => n.isArchived)
            .toList());
  }
}
