import 'package:flutter/material.dart';
import '../../../core/theme.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: ThemeColors.bg(context),
      appBar: AppBar(
        backgroundColor: ThemeColors.bg(context),
        title: const Text('Terms of Service'),
        centerTitle: false,
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(20, 8, 20, 40),
        children: [
          Text(
            'Last updated: 1 January 2025',
            style: TextStyle(
              fontSize: 13,
              color: ThemeColors.textSecondary(context).withOpacity(0.5),
            ),
          ),
          const SizedBox(height: 24),

          _buildSection(
            context,
            title: '1. Acceptance of Terms',
            body:
                'By downloading, installing, or using the AgroEzuran mobile application ("App"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the App.',
          ),

          _buildSection(
            context,
            title: '2. Description of Service',
            body:
                'AgroEzuran is an IoT-based smart farming application that connects to sensor devices to monitor soil moisture, pH levels, temperature, humidity, and water levels. The App also provides automated irrigation control and AI-powered crop advisory features.',
          ),

          _buildSection(
            context,
            title: '3. User Account',
            body:
                'You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorised use of your account. AgroEzuran is not liable for any loss resulting from unauthorised access to your account.',
          ),

          _buildSection(
            context,
            title: '4. Device & Sensor Data',
            body:
                'AgroEzuran collects real-time sensor readings from IoT devices linked to your account. This data is stored securely and used solely to provide the farming advisory and automation services within the App. You retain ownership of all data generated by your devices.',
          ),

          _buildSection(
            context,
            title: '5. Automated Irrigation',
            body:
                'The auto-irrigation feature controls your pump based on sensor thresholds you configure. AgroEzuran is not responsible for any damage to crops, equipment, or property arising from automated pump actions. Always verify your threshold settings before enabling auto mode.',
          ),

          _buildSection(
            context,
            title: '6. AI Advisory Disclaimer',
            body:
                'The AI assistant provides recommendations based on sensor data and general agricultural knowledge. These recommendations are for informational purposes only and do not constitute professional agricultural advice. Always consult a qualified agronomist for critical farming decisions.',
          ),

          _buildSection(
            context,
            title: '7. Prohibited Use',
            body:
                'You agree not to misuse the App, including but not limited to: attempting to gain unauthorised access to other users\' data, reverse engineering the App, or using the App for any unlawful purpose.',
          ),

          _buildSection(
            context,
            title: '8. Service Availability',
            body:
                'AgroEzuran strives to maintain continuous service availability but does not guarantee uninterrupted access. Scheduled maintenance, network issues, or factors beyond our control may result in temporary downtime.',
          ),

          _buildSection(
            context,
            title: '9. Changes to Terms',
            body:
                'We reserve the right to update these Terms at any time. Continued use of the App after changes are posted constitutes your acceptance of the revised Terms.',
          ),

          _buildSection(
            context,
            title: '10. Contact',
            body:
                'If you have any questions about these Terms, please contact us through the Help & Support section in the App.',
          ),
        ],
      ),
    );
  }

  Widget _buildSection(BuildContext context, {required String title, required String body}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontSize: 15,
              fontWeight: FontWeight.w700,
              color: ThemeColors.textPrimary(context),
            ),
          ),
          const SizedBox(height: 8),
          Text(
            body,
            style: TextStyle(
              fontSize: 14,
              height: 1.6,
              color: ThemeColors.textSecondary(context).withOpacity(0.75),
            ),
          ),
        ],
      ),
    );
  }
}
